# PyInstaller spec file for OllamaTUI

block_cipher = None

a = Analysis(
    ['src/ollamatui/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'ollamatui',
        'ollamatui.config',
        'ollamatui.providers',
        'ollamatui.providers.base',
        'ollamatui.providers.local',
        'ollamatui.providers.cloud',
        'ollamatui.providers.factory',
        'ollamatui.tools',
        'ollamatui.tools.base',
        'ollamatui.tools.file',
        'ollamatui.tools.bash',
        'ollamatui.tools.git',
        'ollamatui.tools.web_search',
        'ollamatui.widgets',
        'ollamatui.widgets.chat',
        'ollamatui.widgets.model_selector',
        'ollamatui.widgets.file_tree',
        'ollamatui.sessions',
        'ollamatui.sessions.manager',
        'ollamatui.mcp',
        'ollamatui.mcp.client',
        'textual',
        'textual.widgets',
        'textual.containers',
        'rich',
        'rich.syntax',
        'rich.text',
        'pydantic',
        'pydantic_settings',
        'httpx',
        'ollama',
        'aiosqlite',
        'bs4',
        'lxml',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'cv2',
        'torch',
        'tensorflow',
        'jupyter',
        'notebook',
        'IPython',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ollamatui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    entry_point='ollamatui.main:main',
)
